layout_spectrum: 0.6783406
typography_spectrum: 0.9512501
color:
  saturation: 0.6347017
  lightness: 0.9155464
  brandStrength: 0.489267
  rhythmicContrast: 0.256486
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: 'Gail Davis Armstrong '
